### ISSUE TITLE
getting error while running this project

### ISSUE THREAD

**Issue by Poonam2289** [prakhardogra921/Vehicle-Detection-using-Faster-R-CNN#1]
Hi

I am trying to rum this project but getting errror *'NoneType' object has no attribute 'shape'**

Can you help

**Comment by prakhardogra921** [comment]
NoneType usually means that there is the object being processed is None. 
You have to understand how the data is being loaded. Since this project was trained and tested on an enormous amount of data, it hasn't been uploaded to the github repository and has been mentioned in the ReadMe to download from the source. And you also have to edit certain sections of source code to load it properly for training.
